title: "TwinCAT Libre"
remote_theme: just-the-docs/just-the-docs

search_enabled: true


aux_links:
  "TwinCAT Libre on GitHub":
    - "https://github.com/TwinCAT-Libre"
  "Beckhoff Infosys":
    - "https://infosys.beckhoff.com/index_en.htm"
    
aux_links_new_tab: true
